# v2 sintax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  laravel-api-skeleton-mysql-data:
    driver: local

  # Redis Data
  laravel-api-skeleton-redis-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: laravel-api-skeleton-mysql
    volumes:
      - laravel-api-skeleton-mysql-data:/var/lib/mysql
    ports:
      - "3366:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=laravel-api-skeleton
      - MYSQL_DATABASE=laravel-api-skeleton
      - MYSQL_USER=laravel-api-skeleton
      - MYSQL_PASSWORD=laravel-api-skeleton

  # Redis
  cache:
    image: ambientum/redis:3.2
    container_name: laravel-api-skeleton-redis
    command: --appendonly yes
    volumes:
      - laravel-api-skeleton-redis-data:/data
    ports:
      - "6379:6379"

  # laravel-api-skeleton API (with Caddy)
  api:
    image: ambientum/php:7.0-caddy
    container_name: laravel-api-skeleton-api
    volumes:
      - .:/var/www/app
    ports:
      - "8080:8080"
    links:
      - mysql
      - cache

  # Laravel Queues
  queue:
    image: ambientum/php:7.0
    container_name: laravel-api-skeleton-queue
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - mysql
      - cache